spring:
  zipkin:               # Sleuth-Zipkin config
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
      
eureka:
  client:
    register-with-eureka:false
    fetch-registry:false
      